version: ~> 1.0
language: node_js
os:
 - linux
install:
- 'if [ -n "${COREJS}" ]; then npm install --no-save "core-js@${COREJS}"; fi'
import:
 - ljharb/travis-ci:node/all.yml
 - ljharb/travis-ci:node/pretest.yml
 - ljharb/travis-ci:node/posttest.yml
 - ljharb/travis-ci:node/coverage.yml
matrix:
  include:
    - node_js: "lts/*"
      env: TEST=true COREJS=2
    - node_js: "0.10"
      env: TEST=true COREJS=2
  allow_failures:
    - env: COVERAGE=true
